name: floating_navigation_bar
description: A beautiful highly customizable floating navigation bar
version: 0.0.3
author: Kevin Tailor<kevin7aylor@gmail.com>
homepage: https://github.com/tailoristic/floating_navigation_bar.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
